---
- name: personal | clone dotfiles
  git:
    repo: git@github.com:sethiele/dotfiles.git
    dest: ~/.dotfiles
  tags:
    - personal
    - once

- name: personal | download powerline fonts
  unarchive:
    src: https://github.com/chrissimpkins/Hack/archive/master.zip
    dest: "{{ansible_env.HOME}}/Downloads"
    remote_src: True
  tags:
    - personal
    - once

- name: personal | create font dir
  file:
    path: "{{ansible_env.HOME}}/.local/share/fonts"
    state: directory
  tags:
    - personal
    - once

- name: personal | install font
  copy: 
    src: "{{ansible_env.HOME}}/Downloads/Hack-master/build/ttf/{{item}}"
    dest: "{{ansible_env.HOME}}/.local/share/fonts/{{item}}"
  with_items:
    - Hack-BoldItalic.ttf
    - Hack-Bold.ttf
    - Hack-Italic.ttf
    - Hack-Regular.ttf
  notify:
    - restart fc-cache 
  tags:
    - personal


- name: basics - No Guest User
  copy: 
    src: 99-disable-guest-session.conf
    dest: /etc/lightdm/lightdm.conf.d/99-disable-guest-session.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: software - dconf - set launchbar icon size
  dconf: 
    key: /org/compiz/profiles/unity/plugins/unityshell/icon-size
    int: 20

- name: software - vim - set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  become: yes
  tags:
    - personal
    - once