- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  roles:
    - commons

- name: Install Software
  hosts: local
  connection: local
  roles:
    - software

- name: Personal Settings
  hosts: local
  connection: local
  roles:
    - personal  