---
- name: install basic packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - software-properties-common
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libsqlite3-dev
    - aptitude
    - python-pip
  become: yes

- name: basics - No Guest User
  copy: src=roles/commons/files/99-disable-guest-session.conf dest=/etc/lightdm/lightdm.conf.d/99-disable-guest-session.conf owner=root group=root mode=0644
  become: yes
