---
  - include: software/chrome.yml
  - include: software/dconf.yml
  - include: software/guake.yml
  - include: software/spotify.yml
  - include: software/sublime.yml
  - include: software/tools.yml
  - include: software/vagrant_virtualbox.yml
  - include: software/vpn.yml
