---
- name: software - vim - install
  apt:
    name: vim
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - vim - set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  tags:
    - software
    - once

- name: software - tmux - install
  apt:
    name: tmux
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - tools - filezilla install
  apt:
    name: filezilla
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - tools - indicator-multiload
  apt:
    name: indicator-multiload
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - tools - gnupg2
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - gnupg2
    - gnupg-doc
  become: yes