---
- name: software - vim - install
  apt:
    name: vim
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - vim - set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  become: yes
  tags:
    - software
    - once

- name: software - tmux - install
  apt:
    name: tmux
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - tools - filezilla install
  apt:
    name: filezilla
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - tools - indicator-multiload
  apt:
    name: indicator-multiload
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: software - tools - gnupg2
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - gnupg2
  become: yes

# Packages to enable iPhone hotspot via USB
- name: software - tools - iphone hotspot
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ipheth-utils
    - libimobiledevice-dev
    - libimobiledevice-utils
  become: yes

# Packages to safe cds
- name: software - tools - audio codecs
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - lame
    - vorbis-tools
    - flac
    - wavpack
    - asunder
  become: yes

- name: software - tools - asunder config
  template:
    src: asunder.j2
    dest: "{{ ansible_env.HOME }}/.asunder"

- name: software - tools - lftp
  apt:
    name: lftp
    update_cache: yes
    cache_valid_time: 3600
  become: yes
