---
- name: software | tool | install vim
  apt:
    name: vim
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - tools
    - apt

- name: software | tool | install tmux
  apt:
    name: tmux
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - tools
    - apt

- name: software | tool | install filezilla
  apt:
    name: filezilla
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - tools
    - apt

# Anzeige im Menü
- name: software | tool | indicator-multiload
  apt:
    name: indicator-multiload
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - tools
    - apt

- name: software | tool | install gnupg2
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - gnupg2
  become: yes
  tags:
    - software
    - tools
    - apt

# Packages to enable iPhone hotspot via USB
- name: software | tool | install iphone hotspot
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ipheth-utils
    - libimobiledevice-dev
    - libimobiledevice-utils
  become: yes
  tags:
    - software
    - tools
    - apt

# Packages to safe cds
- name: software | tool | install audio codecs
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - lame
    - vorbis-tools
    - flac
    - wavpack
    - asunder
  become: yes
  tags:
    - software
    - tools
    - apt

- name: software | tool | asunder config
  template:
    src: asunder.j2
    dest: "{{ ansible_env.HOME }}/.asunder"
  tags:
    - software
    - tools

- name: software | tool | lftp
  apt:
    name: lftp
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - tools
    - apt

- name: software | tool | install vlc
  apt:
    name: vlc
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - tools
    - apt

- name: software | tool | gpa GPG GUI
  apt:
    name: gpa
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - tools
    - apt