---
- name: software | virtualbox | install
  apt:
    name: virtualbox
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - virtualbox
    - apt

- name: software | virtualbox | install virtualbox-dkms
  apt:
    name: virtualbox-dkms
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - virtualbox
    - apt

- name: software | vagrant | install
  apt:
    name: vagrant
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - vagrant
    - apt


- name: software | mysql-workbench | install
  apt:
    name: mysql-workbench 
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - software
    - mysql
    - apt

